export const brands = [
  {
    id: "109a66f4-b1a3-45dc-b1e9-9f6912efa928",
    slug: "nike",
    name: "Nike",
    image: "/assets/images/brands/brand1.png",
    type: null,
    featured: true,
    url: "/products/search?brand=nike",
  },
  {
    id: "1f367909-644b-49f3-8e83-d84d20528e7f",
    slug: "under-armour",
    name: "Under Armour",
    image: "/assets/images/brands/brand2.png",
    type: null,
    featured: false,
    url: "/products/search?brand=under-armour",
  },
  {
    id: "077d40ac-fc19-47ff-90b1-f0d46c7b613a",
    slug: "michael-kors",
    name: "Michael Kors",
    image: "/assets/images/brands/brand3.png",
    type: null,
    featured: true,
    url: "/products/search?brand=osiris",
  },
  {
    id: "be171dfc-8d71-4678-90b9-87ef70be0eff",
    slug: "osiris",
    name: "Osiris",
    image: "/assets/images/brands/brand4.png",
    type: null,
    featured: false,
    url: "/products/search?brand=michael-kors",
  },
];
